### ISSUE TITLE
Find a way to account for Clownflare

### ISSUE THREAD

**Issue by brian6932** [Mm2PL/justgrep#9] opened 2022-04-14 21:22 UTC
Cloudflare may block users of justgrep because of the large quantity of requests performed.

`-url https://harambelogs.pl/`
>Error:
`Error while fetching logs: justlog instance responded with 503: "<!DOCTYPE HTML>"`

magichack, ivr, and vtlogs do not have these issues
>EDIT: I fixed the vtlogs issue, it was my bad

**Comment by Mm2PL** [comment] 2022-04-14 21:32
That's probably Cloudflare blocking you

**Comment by brian6932** [comment] 2022-04-14 21:33
https://paste.rs/XVk It seems when curling that the formatting is different from other justlog instances @Mm2PL

**Comment by brian6932** [comment] 2022-04-14 21:33
looks to me like that is the cause 🤷

**Comment by brian6932** [comment] 2022-04-14 21:38
https://logs.magichack.xyz/ also uses Cloudflare, but does not exhibit this issue 🤔

**Comment by Mm2PL** [comment] 2022-04-14 21:44
I don't think this issue is really solvable without asking the owner to disable rate limiting or an instance whose owner is willing to have their logs searched. I can't see any headers that would allow us to obey the limits set out by the site's owner and I don't think the limits are static.

**Comment by zneix** [comment] 2022-04-14 22:30
> [logs.magichack.xyz](https://logs.magichack.xyz/) also uses Cloudflare, but does not exhibit this issue :thinking: 

Well, I know for a fact mm2pl has encountered the same issue in his old bot months ago. I'm sorry for the inconveniences caused by shitty Cloudflare management and incorrect rules set by the domain owner. I'll try to look again at what co-owner might've changed in the rules that affects the log site and in the meantime there's also the secret ""temporary fix"", which I think is enough to close this.

But just to add to the issue - I think that definietly it's rather something that tool shouldn't even try to parse and give up (especially since HTTP status code indicates 5xx, so it could not even be CF, but maybe generic server failure which wouldn't be reliable, also potential fix would/could be very hacky, not clean, etc. etc.)

**Closed** 2022-04-14 22:31 UTC
